#!/usr/bin/env python3
"""zobe.ai token generator — one accent + a mode → a full, WCAG-checked token set.

Usage:
    python3 gen_tokens.py --accent "#0071e3" --mode light [options]

Options:
    --mode   light | dark            (default light)
    --shape  soft | sharp            (default soft → 10px scale; sharp → 0-radius)
    --warm                           warm off-white/off-black instead of cool
    --display "Clash Display"        display typeface (default Clash Display)
    --body    "Inter"                body typeface (default Inter)
    --tailwind                       also emit a Tailwind 4 @theme block
    --report                         print a contrast report to stderr

Emits a filled tokens.css to stdout. stdlib only, no deps.
"""
import argparse
import sys


def hx(c):
    c = c.lstrip("#")
    if len(c) == 3:
        c = "".join(ch * 2 for ch in c)
    return tuple(int(c[i:i + 2], 16) for i in (0, 2, 4))


def hex_str(rgb):
    return "#{:02x}{:02x}{:02x}".format(*(max(0, min(255, round(v))) for v in rgb))


def mix(a, b, t):
    return tuple(a[i] + (b[i] - a[i]) * t for i in range(3))


def lum(rgb):
    def ch(v):
        v /= 255
        return v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4
    r, g, b = (ch(x) for x in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a, b):
    la, lb = lum(a), lum(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def toward(color, target, bg, want=4.5, cap=0.85):
    t = 0.0
    out = color
    while contrast(out, bg) < want and t < cap:
        t += 0.05
        out = mix(color, target, t)
    return out


def main():
    ap = argparse.ArgumentParser(add_help=True)
    ap.add_argument("--accent", required=True)
    ap.add_argument("--mode", choices=["light", "dark"], default="light")
    ap.add_argument("--shape", choices=["soft", "sharp"], default="soft")
    ap.add_argument("--warm", action="store_true")
    ap.add_argument("--display", default="Clash Display")
    ap.add_argument("--body", default="Inter")
    ap.add_argument("--tailwind", action="store_true")
    ap.add_argument("--report", action="store_true")
    a = ap.parse_args()

    accent = hx(a.accent)
    black = (2, 2, 2) if a.warm else (10, 12, 14)
    white = (250, 248, 244) if a.warm else (245, 245, 247)

    if a.mode == "light":
        bg, surface = white, (255, 255, 255)
        ink = (26, 23, 20) if a.warm else (29, 29, 31)
    else:
        bg, surface = black, (21, 21, 21)
        ink = (255, 255, 255)

    accent_strong = toward(accent, (0, 0, 0), bg)          # accent text/button on this bg
    accent_on_dark = toward(accent, (255, 255, 255), black)  # accent on dark surfaces
    accent_tint = mix(accent, bg, 0.88)
    ink_muted = mix(ink, bg, 0.45)
    border = mix(ink, bg, 0.88)

    radius = "0" if a.shape == "sharp" else "0.625rem"
    radius_sm = "0" if a.shape == "sharp" else "0.375rem"

    out = []
    out.append("/* Generated by zobe.ai gen_tokens.py — fill the display font if you have a licensed one. */")
    out.append(":root {")
    out.append(f"  --accent:         {hex_str(accent)};")
    out.append(f"  --accent-strong:  {hex_str(accent_strong)};  /* WCAG-safe for text/buttons */")
    out.append(f"  --accent-tint:    {hex_str(accent_tint)};")
    out.append(f"  --accent-on-dark: {hex_str(accent_on_dark)};")
    out.append("")
    out.append(f"  --bg:        {hex_str(bg)};")
    out.append(f"  --surface:   {hex_str(surface)};")
    out.append(f"  --ink:       {hex_str(ink)};")
    out.append(f"  --ink-muted: {hex_str(ink_muted)};")
    out.append(f"  --border:    {hex_str(border)};")
    out.append("")
    out.append(f'  --font-display: "{a.display}", system-ui, sans-serif;')
    out.append(f'  --font-body:    {a.body}, system-ui, sans-serif;')
    out.append("  --text-sm:      clamp(0.8rem, 0.77rem + 0.2vw, 0.875rem);")
    out.append("  --text-body:    clamp(1rem, 0.96rem + 0.2vw, 1.125rem);")
    out.append("  --text-h2:      clamp(2rem, 1.6rem + 2vw, 3rem);")
    out.append("  --text-h1:      clamp(2.6rem, 2rem + 3vw, 4.25rem);")
    out.append("  --text-display: clamp(3.25rem, 2.2rem + 5.5vw, 7.5rem);")
    out.append("  --tracking-display: -0.03em;")
    out.append("  --tracking-label:   0.14em;")
    out.append("  --leading-display:  1.02;")
    out.append("  --leading-body:     1.45;")
    out.append("")
    out.append("  --section-y: clamp(3rem, 8vw, 7.5rem);")
    out.append("  --measure:   min(92vw, 46rem);")
    out.append("  --band:      min(92vw, 80rem);")
    out.append(f"  --radius:      {radius};")
    out.append(f"  --radius-sm:   {radius_sm};")
    out.append("  --radius-pill: 9999px;")
    out.append("  --shadow-soft: 0 8px 24px rgb(0 0 0 / 0.08);")
    out.append("  --ease:        cubic-bezier(0.4, 0, 0.2, 1);")
    out.append("  --ease-expo:   cubic-bezier(0.165, 0.84, 0.44, 1);")
    out.append("  --dur-fast: 160ms;")
    out.append("  --dur:      280ms;")
    out.append("}")

    if a.tailwind:
        out.append("")
        out.append("/* Tailwind 4 */")
        out.append("@theme {")
        out.append(f"  --color-bg: {hex_str(bg)};")
        out.append(f"  --color-surface: {hex_str(surface)};")
        out.append(f"  --color-ink: {hex_str(ink)};")
        out.append(f"  --color-accent: {hex_str(accent)};")
        out.append(f'  --font-display: "{a.display}", sans-serif;')
        out.append(f"  --radius-DEFAULT: {radius};")
        out.append("  --ease-DEFAULT: cubic-bezier(0.4, 0, 0.2, 1);")
        out.append("}")

    print("\n".join(out))

    if a.report:
        def tag(r):
            return "AAA" if r >= 7 else ("AA" if r >= 4.5 else ("AA-large" if r >= 3 else "FAIL"))
        rows = [
            ("ink / bg", contrast(ink, bg)),
            ("ink-muted / bg", contrast(ink_muted, bg)),
            ("accent / bg", contrast(accent, bg)),
            ("accent-strong / bg", contrast(accent_strong, bg)),
            ("white text / accent btn", contrast((255, 255, 255), accent)),
            ("ink text / accent btn", contrast(ink, accent)),
        ]
        print("\n  contrast report (WCAG):", file=sys.stderr)
        for name, r in rows:
            print(f"    {name:28} {r:4.1f}:1  {tag(r)}", file=sys.stderr)
        print("  → for the accent button, use whichever text (white/ink) passes AA.\n", file=sys.stderr)


if __name__ == "__main__":
    main()
